steps:
  # 1. 构建 Docker 镜像
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/newagent-xswf/dialogflow-webhook", "."]

  # 2. 推送 Docker 镜像到 Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/newagent-xswf/dialogflow-webhook"]

  # 3. 部署到 Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "dialogflow-webhook"
      - "--image=gcr.io/newagent-xswf/dialogflow-webhook"
      - "--platform=managed"
      - "--region=us-central1"
      - "--allow-unauthenticated"

# 允许 Cloud Build 访问 Cloud Run
timeout: 1200s
