steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/dialogflow-webhook', '.' ]
images:
  - 'gcr.io/$PROJECT_ID/dialogflow-webhook'
options:
  logging: CLOUD_LOGGING_ONLY
